"""Initial migration

Revision ID: f38385da05df
Revises: 
Create Date: 2026-04-25 16:08:42.336255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38385da05df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('report_id', sa.String(), nullable=True))
    op.add_column('internal_ledger', sa.Column('report_id', sa.String(), nullable=True))
    op.add_column('reconciliation_matches', sa.Column('report_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'reconciliation_reports', ['report_id'], ['id'])
    op.create_foreign_key(None, 'internal_ledger', 'reconciliation_reports', ['report_id'], ['id'])
    op.create_foreign_key(None, 'reconciliation_matches', 'reconciliation_reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'reconciliation_matches', type_='foreignkey')
    op.drop_constraint(None, 'internal_ledger', type_='foreignkey')
    op.drop_column('transactions', 'report_id')
    op.drop_column('internal_ledger', 'report_id')
    op.drop_column('reconciliation_matches', 'report_id')
    # ### end Alembic commands ###
